# Generated by Django 4.1.7 on 2023-04-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('CASH', 'Cash'), ('BANK TRANSFER', 'Bank Transfer')], default='CASH', max_length=20)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cashflow_date', models.DateField(default='2000-01-01')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.clients')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
