# Generated by Django 4.1.7 on 2023-04-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoices_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='invoices',
            name='products',
            field=models.ManyToManyField(to='invoices.products'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='number',
            field=models.IntegerField(max_length=30, unique=True),
        ),
    ]
