# Generated by Django 4.1.3 on 2022-12-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("description", models.TextField()),
                ("status", models.CharField(max_length=100)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "github"), (1, "gitlab"), (2, "bitbucket")]
                    ),
                ),
                ("url", models.URLField()),
                ("credentials", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
